services:
    db:
        container_name: blog_db
        image: postgres:latest
        environment:
            POSTGRES_DB: "blog"
            POSTGRES_USER: "blog"
            POSTGRES_PASSWORD: "blog"
        volumes:
            - blog_app:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - symfony
    php:
        container_name: blog_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/
        networks:
            - symfony
    nginx:
        container_name: blog_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - "80:80"
        networks:
            - symfony

networks:
    symfony: